fix metric reporting
linkedin/Burrow pull request #638
Opened 2020-06-11 14:46 UTC by fr0stbyte

ran into the same issue as #637 with partitions with 0 offsets - the patch below worked for me

2020-06-19 03:41 UTC, bai commented
/cc @d1egoaz

2020-09-21 10:57 UTC, arthurvanduynhoven commented
@bai Any update on ETA for this MR to be accepted/merged?

2020-09-24 16:51 UTC, d1egoaz requested changes
@fr0stbyte it looks like the why of these can only be found in https://github.com/linkedin/Burrow/issues/637#issuecomment-641517141, I'd rather have this information as part of the commit messages of this PR.  

there is also some new assertion to be made on the tests to check that this PR is doing what is supposed to be doing

2020-09-24 16:51 UTC, d1egoaz commented on core/internal/httpserver/prometheus.go
> +					if partition.Complete >= 1.0 {
could `Complete` be greather than 1, or is this only a percentage and we could use here `== 1.0`?

2020-09-24 16:51 UTC, d1egoaz commented on core/internal/httpserver/prometheus_test.go
>  	assert.Contains(t, promExp, `burrow_kafka_topic_partition_offset{cluster="testcluster",partition="0",topic="testtopic1"} 54`)
wasn't the idea to get a lag report for the topic `incomplete`? I think we are missing and assertion above as  `consumerPartitionLagGauge.With(labels).Set(float64(partition.CurrentLag))` will be called now even if `Complete` is below 1

2020-10-26 21:50 UTC, mwain commented
I came across the same issue earlier this week, sorry i wasn't keeping an eye on the repo
Fix im using is https://github.com/linkedin/Burrow/compare/linkedin:master...mwain:fix-prom-incomplete 

Which is very similar to this one 👍

2020-11-05 13:00 UTC, omaskery commented
Hullo, is there anything I can do to help move this PR forward? :)

2020-11-06 00:51 UTC, fr0stbyte commented
Sorry folks, I have been busy at work, will try to take another pass at this in the following days.

2021-03-29 12:18 UTC, Fran-ELS-AMS commented
I have the same issue and would love to see this PR merged.

Has there been any progress?

2021-04-08 20:30 UTC, fr0stbyte commented
@d1egoaz let me know if the tests added are sufficient or you have other comments

2021-06-29 03:30 UTC, CurtisEppel commented
Going on a full year now - how can I help get this merged? 

Tagging @bai as a code owner.

2021-06-29 03:43 UTC, merged

2021-06-29 03:44 UTC, CurtisEppel commented
Thanks all! 🎉 🚢